name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: self-hosted

    services:
      docker:
        image: docker:latest
        options: >-
          --privileged
          --name docker
          --network host

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker registry
        run: echo "${{ secrets.CI_JOB_TOKEN }}" | docker login -u "${{ secrets.CI_REGISTRY_USER }}" --password-stdin ${{ secrets.CI_REGISTRY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} --tag ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}